import Head from "next/head";
import { Inter } from "@next/font/google";
import Navbar from "../src/components/navbar/navbar";
import HeaderContainer from "../src/components/headerContainer/headerContainer";
import CategoriesGrid from "../src/components/categoriesGrid/categoriesGrid";
import Context from "../libs/context.js";
import RedBanner from "../src/components/redBanner/redBanner";
import CategoriesSlideShow from "../src/components/categoriesSlideShow/categoriesSlideShow";
import Footer from "../src/components/footer/footer";
import ShoppingCart from "../src/components/shoppingCart/shoppingCart";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data, store, categories, footerNavigation }) {
  return (
    <div className="relative h-full">
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <header>
        <Navbar />
        <HeaderContainer data={data} />
      </header>
      <Context.Provider value={store}>
        <main>
          <div className="text-center my-12">
            <h2 className="mb-2 text-4xl font-semibold tracking-wide uppercase">
              FALL READY NOW!
            </h2>
            <p>Everything you need to greet the season in style.</p>
          </div>
          <CategoriesGrid />
          <RedBanner />
          <CategoriesSlideShow data={categories} />
        </main>
      </Context.Provider>
      <footer>
        <Footer data={footerNavigation} />
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const { header, store, categories, footerNavigation } = await import(
    "/data/data.json"
  );

  return {
    props: {
      data: header,
      store: store,
      categories: categories,
      footerNavigation: footerNavigation,
    },
  };
}
